###############################################################################
# File         : lw.S
# Project      : EE180 Lab 2: MIPS
#
# Standards/Formatting:
#   MIPS gas, soft tab, 80 column
#
# Description:
#   Test the functionality of the 'sb' instruction.
#
###############################################################################


    .section .boot, "x"
    .balign 4
    .set    noreorder
    .global boot
    .ent    boot
boot:
    lui     $s0, 0x8002         # Load the base address of the status/test registers
    ori     $s1, $0, 1          # Prepare the 'done' status
    lui     $t0, 0              # Load 0x00003210 to register $t0
    ori     $t0, $t0, 0x3210
    sw      $0, -4($t0) 		#test neg offset	
    lui     $t1, $0, 0xFF01		#A = 0x01FFFFFF
	ori		$t1, $0, 0xFFFF
    sb      $t1, -4($t0)		# the actual value stored should be 1
    lw      $t1, -4($t0)
    sw      $t1, 4($s0)         # Set the test result
    sw      $s1, 0($s0)         # Set 'done'

$done:
    j       $done
    nop

    .end boot
